export const Users = [
    {
      id:1,
      profilePicture: "/Pictures/People/1.png",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "/Pictures/People/2.png",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "/Pictures/People/3.png",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "/Pictures/People/4.png",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "/Pictures/People/5.png",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "/Pictures/People/6.png",
      username: "Shirley Beak",
    },
    {
      id:7,
      profilePicture: "/Pictures/People/7.png",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "/Pictures/People/8.png",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "/Pictures/People/9.png",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "/Pictures/People/10.png",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Postss = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "/Pictures/Posts/11.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "/Pictures/Posts/12.png",
      date: "15 mins ago",
      userId: 1,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Great job folks!",
      photo: "/Pictures/Posts/13.png",
      date: "1 hour ago",
      userId: 1,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "/Pictures/Posts/14.png",
      date: "4 hours ago",
      userId: 1,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "/Pictures/Posts/15.png",
      date: "5 hours ago",
      userId: 1,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "/Pictures/Posts/16.png",
      date: "1 day ago",
      userId: 1,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "/Pictures/Posts/17.png",
      date: "2 days ago",
      userId: 1,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "/Pictures/Posts/18.png",
      date: "3 days ago",
      userId: 1,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "/Pictures/Posts/19.png",
      date: "5 days ago",
      userId: 1,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "/Pictures/Posts/20.png",
      date: "1 week ago",
      userId: 1,
      like: 104,
      comment: 12,
    },
  ];